lib/src/attributes/animation/animated_mix.dart
lib/src/attributes/animation/animated_text.dart
lib/src/attributes/attributes_api.dart
lib/src/attributes/primitives/icon/icon_size.dart
lib/src/attributes/primitives/text/text_color.dart
lib/src/mixer/mixer.dart
lib/src/widgets/primitives/box.dart
lib/src/widgets/primitives/icon.dart
lib/src/widgets/primitives/text.dart

Continuation of #7 and #9
both `iconColor` and `iconSize` attributes can be animated.
```dart
IconMix(
Mix(
iconColor(Colors.primary).animated(),
disabled(Mix(iconColor(Colors.grey).animated())),
hovering(Mix(iconColor(Colors.primary.shade400).animated())),
pressing(Mix(iconColor(Colors.primary.shade600).animated())),
),
icon: Icons.add,
)
```
When `animatedText()` is added to a mix, the whole `Text` is animated.
```dart
TextMix(
Mix(
animatedText(),
textColor(Colors.primary),
disabled(Mix(textColor(Colors.grey))),
hovering(Mix(textColor(Colors.primary.shade400))),
pressing(Mix(textColor(Colors.primary.shade600))),
),
text: 'MY TEXT',
)
```

Icon and Text Animation

---

demo/lib/views/cards.dart
lib/src/headless/card.dart
lib/src/headless/exports.dart

Usage:
```dart
CardX(
children: [
TextMix(
titleContent,
variant: title,
),
TextMix(
paragraphContent,
variant: paragraph,
),
],
)
```

Implement headless card

---

demo/lib/views/cards.dart
demo/pubspec.lock
lib/src/headless/chip.dart
lib/src/headless/exports.dart
pubspec.lock

```dart
ChipX(
children: const [IconMix(icon: Icons.add), TextMix('Lorem')],
onPressed: () => debugPrint('lorem'),
),
```

Headless chip

---

website/pages/_document.js
website/pages/docs/getting-started/concepts.mdx
website/pages/docs/getting-started/mixing.mdx
website/styles.css

I've worked over primarily the 'Concepts' page, for starters.  Also changed some of the header styling to something I think works better.
Might have gotten carried away.
Look it over and we can discuss.
Do you have a git Project set up for this?
thanx,
rickb

Initial doc changes

---

lib/mix.dart

Exposed variants

---

demo/lib/views/button_preview.dart
demo/lib/views/pressable_preview.dart
lib/src/headless/alert_dialog.dart
lib/src/headless/exports.dart

Based on https://www.radix-ui.com/docs/primitives/components/alert-dialog
Usage:
```dart
showDialog(
context,
builder: (context) {
return AlertDialogX(
content: [
TextMix('THIS IS THE TITLE', variant: title),
TextMix('THIS IS THE CONTENT', variant: paragraph),
],
actions: [],
);
},
);
```

Headless Alert Dialog

---

website/pages/docs/core-concepts/attributes-and-utilities.mdx

Just replaced with right qualifier.

Update Padding wording

---

lib/src/attributes/box/box.attributes.dart
lib/src/attributes/box/box.props.dart
lib/src/attributes/box/box.utils.dart
lib/src/attributes/box/box_short.utils.dart

Implemented Box Gradient

---

lib/src/attributes/text/text.utils.dart
lib/src/attributes/text/text_short.utils.dart

Uncommented fontWeight

---

lib/src/mixer/mix_context.dart

This adjusted the priority for Mixes inherited from parents. #48

Prioritized defined mix over inherited

---

demo/lib/app_shell.dart
lib/src/theme/mix_theme.dart
lib/src/theme/refs/color_ref.dart
lib/src/theme/refs/refs.dart
lib/src/theme/refs/text_style_ref.dart
lib/src/theme/tokens/breakpoints_token.dart
lib/src/theme/tokens/space_token.dart
lib/src/theme/tokens/text_theme_tokens.dart
test/testing_utils.dart

- Removed `.default` getters where possible and replaced them with factory constructors
- Removed `.merge` where it was irrelevant and replaced it with `.copyWith`
- Replace `._` constructors with `.raw` constructors
- Added equality and `toString` when relevant

Mix theme updates

---

lib/src/attributes/box/box.utils.dart
lib/src/attributes/box/box_short.utils.dart

Fixes #55
```dart
final mix = Mix(
r(10.0),
);
```

`r` short utility for `rounded`

---

demo/lib/app_shell.dart
demo/lib/views/cards.dart
lib/src/helpers/extensions.dart

Makes the following syntax possible:
```dart
final mix = Mix(
(true)( // [condition]
bgColor(Colors.blue), // this is only executed if [condition] is true
),
);
```

Implement BoolExtension

---

pubspec.lock
website/pages/docs/headless-widgets/alert-dialog.mdx
website/pages/docs/headless-widgets/card.mdx
website/pages/docs/headless-widgets/checkbox.mdx
website/pages/docs/headless-widgets/chip.mdx
website/pages/docs/headless-widgets/introduction.mdx
website/pages/docs/headless-widgets/meta.json
website/pages/docs/headless-widgets/radio-button.mdx
website/pages/docs/headless-widgets/switch.mdx
website/pages/docs/meta.json

- Headless Widgets
- Introduction
- Alert Dialog
- Card
- Checkbox
- Chip
- Radio Button
- Switch

Headless Widgets documentation

---

demo/lib/docs/docs.dart
demo/lib/docs/headless/alert_dialog_x.dart
demo/lib/docs/headless/card_x.dart
demo/lib/docs/headless/checkbox_x.dart
demo/lib/docs/headless/chip_x.dart
demo/lib/main.dart
demo/pubspec.lock
demo/pubspec.yaml

- **REGRESSION** Use hash url strategy, since github pages fail when not using it
- Added docs for headless widgets

Demo app updates

---

.github/workflows/version-deploy.yml
pubspec.yaml

Fixes #96
https://github.com/google/dart_cli_pkg/blob/main/doc/pub.md

Deploy on release

---

.github/workflows/version-deploy.yml

#96. Follow-up of #101. Unblocks #100 
https://github.com/k-paxian/dart-package-publisher
https://github.com/bdlukaa/mix/actions/runs/3324681945/jobs/5496629270

Update deploy to pub

---

website/pages/docs/concepts/variants.mdx

`when` variant docs

---

lib/src/widgets/box/box.attributes.dart

The animations wasn't being applied

Bugfix on box decorators

---

README.md
benchmarks/lib/factoring.dart
benchmarks/lib/values.dart
benchmarks/pubspec.lock
demo/lib/components/examples/box/box.mix.dart
demo/lib/docs/variants/and_operator.dart
demo/lib/docs/variants/catalog/pressable.dart
demo/lib/docs/variants/default.dart
demo/lib/docs/variants/or_operator.dart
demo/lib/main.dart
demo/lib/views/basic_example.dart
demo/lib/views/button_preview.dart
demo/lib/views/design_token_example.dart
demo/lib/views/example.dart
demo/pubspec.lock
pubspec.lock
test/widgets/box_test.dart

This PR updates the demo and the README to use non-deprecated behavior

Fix Demo Deprecations

---

lib/src/decorators/built_in_decorators/clip_decorator.dart

Fix nullable borderRadius (#126)

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

Add github template to improve the development flow

Add github templates

---

demo/lib/views/button_example.dart
lib/src/deprecations.dart
lib/src/factory/style_mix.dart
test/src/factory/style_mix_test.dart
test/src/variants/variant_operation_test.dart
test/src/variants/variant_test.dart
website/pages/docs/guides/variants.mdx

* Rename the API to apply variants in style;
* Update `Variant` documentation.
* New section about "Combine Operators"

Updating API and Variant documentation

---

demo/lib/components/box.dart
demo/lib/views/basic_example.dart
demo/lib/views/button_example.dart
demo/lib/views/example.dart
demo/lib/views/layout_example.dart
demo/lib/views/variants.dart
example/README.md
lib/src/deprecations.dart
lib/src/specs/container/box_util.dart
test/bechmarks/widget_build_test.dart
website/pages/docs/guides/styled-widgets.mdx
website/pages/docs/guides/styling.mdx
website/pages/docs/guides/variants.mdx
website/pages/docs/introduction/comparison.mdx
website/pages/docs/introduction/getting-started.mdx

* Modify the API to separate the border and borderRadius properties
- **API change** (breaking change which modify a functionality)

Change border radius api

---

analysis_options.yaml
lib/src/attributes/border/border_dto.dart
lib/src/attributes/border/shape_border_dto.dart
lib/src/attributes/border/shape_border_util.dart
lib/src/attributes/decoration/decoration_dto.dart
lib/src/attributes/decoration/decoration_util.dart
lib/src/attributes/scalars/scalar_util.dart
test/src/attributes/border/shape_border_dto_test.dart
test/src/attributes/decoration/decoration_dto_test.dart
test/src/attributes/decoration/decoration_util_test.dart
test/src/attributes/scalars/scalar_util_test.dart
test/src/core/extensions/values_ext_test.dart

Better support for ShapeDecoration and ShapeBorders. This will allow better composability and support for custom border composition

Better support for ShapeBorder

---

lib/src/attributes/decoration/decoration_dto.dart
lib/src/attributes/decoration/decoration_util.dart

Added missing `backgroundBlendMode` property to BoxDecoration
- **Chore** (updating grunt tasks etc; no production code change)

Added backgroundBlendMode to decoration

---

.github/workflows/test.yml
lib/src/utils/style_recipe.dart

- Recreate the test pipeline. Now we have extra validations following the flowchat below:

Add new job to pipeline

---

lib/src/specs/flex/flex_widget.dart
test/src/specs/flex/flex_widget_test.dart

- Change the gap implementation using `SizedBox` instead of `Padding`

Fix issue where the 'gap' attribute does not working as expected when there is a Flexible Widget

---

.github/workflows/test.yml
analysis_options.yaml
test/helpers/string_ext_test.dart
test/src/theme/material/material_tokens_test.dart

Setup oss license for DCM github action

Update dcm action

---

lib/src/decorators/widget_decorator_widget.dart
lib/src/decorators/widget_decorators.dart
lib/src/decorators/widget_decorators_util.dart
test/src/attributes/border/border_radius_dto_test.dart
test/src/attributes/border/shape_border_dto_test.dart
test/src/attributes/decoration/decoration_dto_test.dart
test/src/attributes/decoration/decoration_util_test.dart
test/src/attributes/scalars/scalar_util_test.dart
test/src/core/extensions/color_ext_test.dart
test/src/decorators/widget_decorators_test.dart
test/src/decorators/widget_decorators_util_test.dart
website/pages/docs/guides/decorators.mdx

- Add IntrinsicHeightDecorator and IntrinsicWidthDecorator

Add IntrinsicHeight and IntrinsicWidth

---

lib/src/specs/container/box_widget.dart
lib/src/specs/icon/icon_widget.dart
lib/src/specs/stack/stack_widget.dart

resolves #187
- implement support for decorations in AnimatedBox, AnimatedIcon and StyledStack

implement support for decorations in AnimatedBox, AnimatedIcon and StyledStack

---

.github/workflows/test.yml

Optimized analyze workflow with remix

Optimized analyze workflow

---

lib/src/specs/stack/stack_widget.dart
pubspec.lock
test/src/specs/container/box_widget_test.dart
test/src/specs/flex/flex_widget_test.dart
test/src/specs/icon/icon_widget_test.dart
test/src/specs/image/image_widget_test.dart
test/src/specs/stack/stack_widget_test.dart
test/src/specs/text/text_widget_test.dart

- Add test "should apply decorators only once" for all widgets
- Fix ZBox widget

Add test "StyledWidgets should apply decorators only once"

---

website/pages/docs/guides/_meta.json
website/pages/docs/guides/supporting-new-widgets.mdx

- Change `_meta.json` that index the guides

Fix duplicated tab

---

.github/workflows/test.yml

- Add a new condition to execute pipeline: Should execute only if specific folders were changed

New conditions to pipeline execution

---

lib/src/factory/style_mix.dart
website/pages/docs/guides/_meta.json
website/pages/docs/guides/animations.mdx

- Create documentation for animation

document animations

---

test/src/widgets/pressable/pressable_widget_test.dart

- I created more test cases for Pressable Variables

Test cases for Pressable Variables

---

lib/src/attributes/scalars/scalar_util.dart
lib/src/decorators/widget_decorators_util.dart
lib/src/specs/container/box_spec.dart
lib/src/specs/container/box_util.dart
lib/src/specs/flex/flex_util.dart
lib/src/specs/icon/icon_util.dart
lib/src/specs/image/image_util.dart
lib/src/specs/stack/stack_util.dart
lib/src/specs/text/text_util.dart
test/src/specs/container/box_util_test.dart
test/src/specs/flex/flex_util_test.dart

Allow extension of utils

---

lib/src/specs/container/box_widget.dart
lib/src/specs/icon/icon_spec.dart
lib/src/specs/icon/icon_widget.dart
lib/src/specs/image/image_spec.dart
lib/src/specs/image/image_widget.dart
lib/src/specs/stack/stack_widget.dart
lib/src/specs/text/text_widget.dart
test/src/specs/container/box_widget_test.dart
test/src/specs/text/text_widget_test.dart

Finished clean up spec widgets

Finished widet spec implementations

---

lib/src/factory/style_mix.dart
lib/src/variants/variant.dart
test/src/factory/style_mix_test.dart

- Every variant has a property called `value`.

implement Variant Priorities

---

lib/src/factory/style_mix.dart
lib/src/specs/icon/icon_util.dart
lib/src/specs/image/image_util.dart
lib/src/specs/text/text_util.dart
test/src/factory/style_mix_test.dart

- Align utilities naming
- AnimatedStyle.applyVariants should return an AnimatedStyle.
- **Bug fix**
- **Test**

Small fixes

---

lib/src/attributes/spacing/spacing_util.dart
lib/src/deprecations.dart
lib/src/theme/mix/mix_tokens.dart
lib/src/theme/mix_theme.dart
lib/src/theme/tokens/radius_token.dart
lib/src/theme/tokens/space_token.dart
lib/src/theme/tokens/token_util.dart
test/src/attributes/nested_style/nested_style_attribute_test.dart
test/src/theme/mix_theme_test.dart
test/src/theme/tokens/radius_token_test.dart
test/src/theme/tokens/space_token_test.dart
test/src/theme/tokens/text_style_token_test.dart

- Remove pre-implemented Space and Radius Tokens
- Remove tokens utilities for Space and Radius
- Rename space to spaces
- **New feature**
- **Test**

Clean up design tokens pre implemented

---

lib/src/deprecations.dart
lib/src/specs/box/box_widget.dart

removing typedef StyledContainer

---

lib/src/core/attribute.dart
lib/src/factory/mix_provider_data.dart
lib/src/helpers/compare_mixin.dart
lib/src/utils/context_variant_util/on_breakpoint_util.dart
lib/src/utils/context_variant_util/on_brightness_util.dart
lib/src/utils/context_variant_util/on_directionality_util.dart
lib/src/utils/context_variant_util/on_helper_util.dart
lib/src/utils/context_variant_util/on_orientation_util.dart
lib/src/variants/variant.dart
lib/src/widgets/pressable/pressable_util.dart
test/helpers/testing_utils.dart
test/src/attributes/variant_attribute_test.dart
test/src/factory/mix_provider_data_test.dart
test/src/factory/style_mix_test.dart
test/src/helpers/compare_mixin_test.dart
test/src/specs/image/image_widget_test.dart
test/src/utils/context_variant_util/on_breakpoint_util_test.dart
test/src/utils/context_variant_util/on_brightness_util_test.dart
test/src/utils/context_variant_util/on_directionality_util_test.dart
test/src/utils/context_variant_util/on_helper_util_test.dart
test/src/utils/context_variant_util/on_orientation_util_test.dart
test/src/utils/context_variant_util_test.dart
test/src/variants/variant_test.dart
test/src/widgets/pressable/pressable_util_test.dart
test/src/widgets/pressable/pressable_widget_test.dart
website/pages/docs/guides/variants.mdx

- Update variant documentation

Update Variant documentation

---

lib/src/helpers/lerp_helpers.dart
lib/src/modifiers/clip_widget_modifier.dart
lib/src/modifiers/rotated_box_widget_modifier.dart
lib/src/modifiers/transform_widget_modifier.dart
lib/src/specs/box/box_spec.dart
lib/src/specs/icon/icon_spec.dart
lib/src/specs/stack/stack_spec.dart

- Align the usage of `lerp` methods

align lerp usage

---

lib/src/attributes/nested_style/nested_style_attribute.dart
lib/src/factory/style_mix.dart
test/src/factory/style_mix_test.dart

- Create an alias to NestedStyleAttributes.

Group attributes

---

packages/mix_lint/lib/mix_lint.dart
packages/mix_lint/lib/src/lints/avoid_empty_style.dart
packages/mix_lint_test/analysis_options.yaml
packages/mix_lint_test/pubspec.lock
packages/mix_lint_test/pubspec.yaml
packages/mix_lint_test/test/lints/avoid_empty_style.dart

create a new lint rule avoid_empty_style

---

website/pages/_meta.json
website/pages/lints/_meta.json
website/pages/lints/lints/_meta.json
website/pages/lints/lints/avoid_empty_style.md
website/pages/lints/lints/avoid_variant_inside_context_variant.md
website/pages/lints/lints/avoid_variant_inside_context_variant.mdx
website/pages/lints/lints/externalize_token_instantiation.md
website/pages/lints/lints/externalize_variant_instantiation.md
website/pages/lints/lints/order_attributes_in_style.md

Create a section "Lints" that contains a description of all the rules
- Configure the website to receive the new section
- Move all docs of lints from mix_lint package to the website project

Create lint section

---

packages/mix/lib/src/attributes/border/border_dto.g.dart
packages/mix/lib/src/attributes/border/border_radius_dto.g.dart
packages/mix/lib/src/attributes/border/shape_border_dto.g.dart
packages/mix/lib/src/attributes/constraints/constraints_dto.g.dart
packages/mix/lib/src/attributes/decoration/decoration_dto.g.dart
packages/mix/lib/src/attributes/decoration/image/decoration_image_dto.g.dart
packages/mix/lib/src/attributes/gradient/gradient_dto.g.dart
packages/mix/lib/src/attributes/shadow/shadow_dto.g.dart
packages/mix/lib/src/attributes/strut_style/strut_style_dto.g.dart
packages/mix/lib/src/attributes/text_style/text_style_dto.g.dart
packages/mix/lib/src/specs/box/box_spec.dart
packages/mix/lib/src/specs/box/box_spec.g.dart
packages/mix/lib/src/specs/flex/flex_spec.g.dart
packages/mix/lib/src/specs/icon/icon_spec.g.dart
packages/mix/lib/src/specs/image/image_spec.g.dart
packages/mix/lib/src/specs/stack/stack_spec.g.dart
packages/mix/lib/src/specs/text/text_spec.g.dart
packages/mix_builder/lib/src/builders/dto/class_utility_dto.dart
packages/mix_builder/lib/src/builders/dto/extension_value.dart
packages/mix_builder/lib/src/builders/dto/mixin_dto.dart
packages/mix_builder/lib/src/builders/method_lerp_builder.dart
packages/mix_builder/lib/src/builders/method_merge.dart
packages/mix_builder/lib/src/builders/method_resolve.dart
packages/mix_builder/lib/src/builders/spec/class_attribute_spec.dart
packages/mix_builder/lib/src/builders/spec/class_spec_utility.dart
packages/mix_builder/lib/src/builders/spec/class_tween_spec.dart
packages/mix_builder/lib/src/builders/spec/mixin_spec.dart
packages/mix_builder/lib/src/helpers/builder_utils.dart
packages/mix_builder/lib/src/helpers/helpers.dart

Improved auto generated comments
- Improved nullable behavior for value extensions on code generation
- Dynamic comments for code gen.

Improved comments

---

packages/mix/lib/src/specs/box/box_spec.g.dart
packages/mix/lib/src/specs/flex/flex_spec.g.dart
packages/mix/lib/src/specs/icon/icon_spec.g.dart
packages/mix/lib/src/specs/image/image_spec.g.dart
packages/mix/lib/src/specs/stack/stack_spec.g.dart
packages/mix/lib/src/specs/text/text_spec.g.dart
packages/mix_generator/lib/src/builders/method_lerp_builder.dart
packages/mix_generator/lib/src/helpers/field_info.dart

Added support for Spec Attributes to mix_generator.

Added support for spec attributes

---

packages/mix/lib/src/specs/box/box_spec.dart
packages/mix/lib/src/specs/flex/flex_spec.dart
packages/mix/lib/src/specs/icon/icon_spec.dart
packages/mix/lib/src/specs/image/image_spec.dart
packages/mix/lib/src/specs/stack/stack_spec.dart
packages/mix/lib/src/specs/text/text_spec.dart

Added call methdo to Specs to help with creation of styled widgets.

Added spec call method

---

.fvmrc
.github/actions/test/action.yml
.github/workflows/test.yml
melos.yaml

- Added FVM to melos and pipeline

Updated pipeline to use fvm

---

packages/mix/lib/src/attributes/border/border_dto.dart
packages/mix/lib/src/attributes/border/border_dto.g.dart
packages/mix/lib/src/attributes/border/border_radius_dto.g.dart
packages/mix/lib/src/attributes/border/shape_border_dto.dart
packages/mix/lib/src/attributes/border/shape_border_dto.g.dart
packages/mix/lib/src/attributes/constraints/constraints_dto.g.dart
packages/mix/lib/src/attributes/decoration/decoration_dto.g.dart
packages/mix/lib/src/attributes/decoration/image/decoration_image_dto.g.dart
packages/mix/lib/src/attributes/gradient/gradient_dto.dart
packages/mix/lib/src/attributes/gradient/gradient_dto.g.dart
packages/mix/lib/src/attributes/shadow/shadow_dto.dart
packages/mix/lib/src/attributes/shadow/shadow_dto.g.dart
packages/mix/lib/src/attributes/spacing/edge_insets_dto.g.dart
packages/mix/lib/src/attributes/strut_style/strut_style_dto.g.dart
packages/mix_generator/lib/src/builders/dto/extension_value.dart
packages/mix_generator/lib/src/mixable_dto_generator.dart

mix_generator now generates a List of the resolver value of a DTO

mix_generator: Generate  List of value extension of a Dto

---

website/components/HomeContent.tsx

When the website is opened on small devices it should be responsive.
- On small devices, the buttons on the interface are shown as a column instead of in a row.

fix: website resposiveness

---

.github/actions/test/action.yml
.github/workflows/changelog.yml
.github/workflows/publish.yml
melos.yaml

#298 
- Rewrite the publish pipeline
- Modify the publishing pipeline to use Melos
- Create a script to run before the publish

chore: rewrite publish pipeline to use Melos

---

website/pages/docs/tutorials/theming.mdx

Change the mention of `of` method to `ref` to match the example code above.
Is it related to any opened issue? No
Update documentation text to match example code above
Is there any additional context or documentation that might be helpful for reviewers? No

docs: Update theming.mdx tutorial

---

packages/mix/lib/src/modifiers/internal/render_widget_modifier.dart
packages/mix/lib/src/specs/flex/flex_spec.dart
packages/mix/lib/src/specs/flex/flex_widget.dart
packages/mix/lib/src/specs/stack/stack_spec.dart
packages/mix/lib/src/specs/stack/stack_widget.dart
packages/mix/test/helpers/override_modifiers_order.dart
packages/mix/test/modifiers/render_widget_modifier_test.dart
packages/mix/test/src/specs/box/box_widget_test.dart
packages/mix/test/src/specs/flex/flex_widget_test.dart
packages/mix/test/src/specs/icon/icon_widget_test.dart
packages/mix/test/src/specs/image/image_widget_test.dart
packages/mix/test/src/specs/stack/stack_widget_test.dart

- Fix animation for attributes of Stack and Flex;
- Add tests for the order of modifiers
- Every StyledWidget is built using the respective Spec callable
- Create `AnimatedSpecWidgets` for Stack and Flex

fix: animations of Stack and Flex

---

.github/workflows/test.yml
packages/mix/lib/src/specs/box/box_spec.dart
packages/mix/lib/src/specs/box/box_spec.g.dart
packages/mix/lib/src/specs/flex/flex_spec.dart
packages/mix/lib/src/specs/flex/flex_spec.g.dart
packages/mix/lib/src/specs/icon/icon_spec.dart
packages/mix/lib/src/specs/icon/icon_spec.g.dart
packages/mix/lib/src/specs/image/image_spec.dart
packages/mix/lib/src/specs/image/image_spec.g.dart
packages/mix/lib/src/specs/stack/stack_spec.dart
packages/mix/lib/src/specs/stack/stack_spec.g.dart
packages/mix/lib/src/specs/text/text_spec.dart
packages/mix/lib/src/specs/text/text_spec.g.dart
packages/mix/pubspec.yaml
packages/mix_generator/lib/src/builders/method_debug_fill_properties.dart
packages/mix_generator/lib/src/builders/method_merge.dart

- Fixes requested by lint
- Remove nullable
- Add defaultValue param to generated code

refactor(mix_generator): fix lints

---

.github/workflows/changelog.yml
.github/workflows/publish.yml

Improvements for publish pipeline
- update publish pipeline

ci: improvements for publish pipeline

---

packages/mix/lib/src/modifiers/align_widget_modifier.g.dart
packages/mix/lib/src/modifiers/aspect_ratio_widget_modifier.g.dart
packages/mix/lib/src/modifiers/clip_widget_modifier.g.dart
packages/mix/lib/src/modifiers/flexible_widget_modifier.g.dart
packages/mix/lib/src/modifiers/fractionally_sized_box_widget_modifier.g.dart
packages/mix/lib/src/modifiers/opacity_widget_modifier.g.dart
packages/mix/lib/src/modifiers/padding_widget_modifier.g.dart
packages/mix/lib/src/modifiers/rotated_box_widget_modifier.g.dart
packages/mix/lib/src/modifiers/sized_box_widget_modifier.g.dart
packages/mix/lib/src/modifiers/transform_widget_modifier.g.dart
packages/mix/lib/src/modifiers/visibility_widget_modifier.g.dart
packages/mix/lib/src/specs/box/box_spec.g.dart
packages/mix/lib/src/specs/flex/flex_spec.g.dart
packages/mix/lib/src/specs/icon/icon_spec.g.dart
packages/mix/lib/src/specs/image/image_spec.g.dart
packages/mix/lib/src/specs/stack/stack_spec.g.dart
packages/mix/lib/src/specs/text/text_spec.g.dart
packages/mix_generator/lib/src/builders/method_debug_fill_properties.dart
packages/remix/lib/components/avatar/avatar_spec.g.dart
packages/remix/lib/components/badge/badge_spec.g.dart
packages/remix/lib/components/button/button_spec.g.dart
packages/remix/lib/components/callout/callout_spec.g.dart
packages/remix/lib/components/card/card_spec.g.dart
packages/remix/lib/components/checkbox/checkbox_spec.g.dart
packages/remix/lib/components/progress/progress_spec.g.dart
packages/remix/lib/components/radio/radio_spec.g.dart
packages/remix/lib/components/spinner/spinner_spec.g.dart
packages/remix/lib/components/switch/switch_spec.g.dart
website/pages/docs/guides/design-token.mdx

Add a section specifically for MixThemeData

docs: improve mix theme data features explanations

---

packages/mix/lib/src/attributes/decoration/decoration_dto.dart
packages/mix/lib/src/attributes/enum/enum_util.dart
packages/mix/lib/src/attributes/enum/enum_util.g.dart
packages/mix/lib/src/attributes/scalars/scalar_util.dart
packages/mix/lib/src/attributes/scalars/scalar_util.g.dart

Added some missing Table utilities, and DecoratorUtility

refactor: Added missing utilities

---

.github/workflows/publish.yml
packages/mix/lib/src/attributes/spacing/spacing_util.dart
packages/mix/lib/src/core/widget_state/widget_state_controller.dart
packages/mix/lib/src/variants/context_variant_util/on_util.dart
packages/mix/lib/src/widgets/pressable_widget.dart

Added missing Widget state utilities and added controller to Pressable.

fix: Added missing widget state utilities

---

packages/mix/lib/src/theme/tokens/breakpoints_token.dart
packages/mix/lib/src/variants/context_variant_util/on_breakpoint_util.dart
packages/mix/lib/src/variants/context_variant_util/on_util.dart
packages/mix/test/src/variants/context_variant_util/on_breakpoint_util_test.dart

An exception can be thrown when using a breakpoint token variant and merging them.

fix: breakpoint utility merge exception

---

website/pages/docs/tutorials/theming.md

- Some items on this documentation were deprecated.
- I remove the extensions of `TokenUtil`

docs: review the theming documentation

---

packages/mix/lib/src/core/helpers.dart
packages/mix/lib/src/specs/icon/icon_spec.g.dart
packages/mix_generator/lib/src/builders/method_lerp_builder.dart
packages/mix_generator/lib/src/helpers/builder_utils.dart

- The shadow list animation wasn't working.
- Add a custom list specific to `List<Shadow>`

fix: Shadow list animation

---

examples/todo_list/pubspec.yaml

- Update google_fonts in examples

chore: Update google fonts

---

website/pages/docs/overview/utility-first.mdx

Is it related to any opened issue?
Please summarize the changes.

docs: Fix an outdated comment

---

website/pages/docs/utilities/text-utilities.md

There is `$` missing in some dart code example
I add `$`.

docs: Adding `$` sign in dart code example

---

packages/mix/lib/src/modifiers/transform_widget_modifier.dart
packages/mix/test/src/modifiers/transform_widget_modifier_test.dart

- Add translate utility to `TransformModifierSpecUtility`
- Add translate method

feat: transform.translate

---

packages/mix/lib/src/attributes/border/border_dto.dart
packages/mix/lib/src/attributes/border/border_dto.g.dart
packages/mix/lib/src/attributes/scalars/scalar_util.dart

- Create a specific utility for BorderAlign
- Create `StrokeAlignUtility`
- Update the `strokeAlign` parameter

feat: Create StrokeAlignUtility

---

packages/remix/demo/lib/components/card_use_case.dart
packages/remix/demo/lib/components/select_use_case.dart
packages/remix/demo/lib/components/spinner_use_case.dart
packages/remix/demo/lib/helpers/knob_builder.dart
packages/remix/demo/lib/main.dart
packages/remix/lib/src/components/accordion/accordion_style.dart
packages/remix/lib/src/components/avatar/avatar_style.dart
packages/remix/lib/src/components/badge/badge_style.dart
packages/remix/lib/src/components/button/button_style.dart
packages/remix/lib/src/components/callout/callout_style.dart
packages/remix/lib/src/components/card/card_style.dart
packages/remix/lib/src/components/checkbox/checkbox_style.dart
packages/remix/lib/src/components/icon_button/icon_button_style.dart
packages/remix/lib/src/components/progress/progress_style.dart
packages/remix/lib/src/components/radio/radio_style.dart
packages/remix/lib/src/components/segmented_control/segmented_control_style.dart
packages/remix/lib/src/components/select/select_style.dart
packages/remix/lib/src/components/spinner/spinner_style.dart
packages/remix/lib/src/components/switch/switch_style.dart
packages/remix/lib/src/theme/remix_theme.dart

- Create dark base theme for Remix 
- Each component receive dark style

feat: Create dark base theme for Remix

---

packages/remix/demo/lib/components/card_use_case.dart
packages/remix/lib/src/components/badge/badge_style.dart
packages/remix/lib/src/components/button/button_style.dart
packages/remix/lib/src/components/card/card.dart
packages/remix/lib/src/components/card/card.g.dart
packages/remix/lib/src/components/card/card_style.dart
packages/remix/lib/src/components/card/card_widget.dart
packages/remix/lib/src/components/radio/radio_style.dart
packages/remix/test/components/card/card_widget_test.dart

Replace parameter children from Card to child.
- Replace parameter children from Card to child.

feat: Card has child instead of children parameter

---

packages/remix/lib/src/components/toast/toast_layer.dart
packages/remix/lib/src/components/toast/toast_style.dart
packages/remix/lib/src/theme/remix_theme.dart

- Everytime that toast need to rebuild the animation was being triggered, so this PR fix it. Additionally, I add some new methods
- Fix the animation trigger
- Add a scenario when the animation is equals to `Duration.zero`

fix: Toast rerunning animation

---

packages/mix/lib/src/theme/tokens/breakpoints_token.dart
packages/mix/lib/src/theme/tokens/color_token.dart
packages/mix/lib/src/theme/tokens/radius_token.dart
packages/mix/lib/src/theme/tokens/text_style_token.dart
website/pages/docs/guides/design-token.mdx

#536 
Add a section explaining the TokenResolver feature and its advantages.
- Modify the design-token.mdx 

docs: Add section for `TokenResolver`

---

docs.json
docs/button.mdx
docs/index.mdx
packages/naked/example/.metadata
packages/naked/example/lib/api/naked_button.0.dart
packages/naked/example/lib/main.dart
packages/naked/lib/src/naked_button.dart

Setup docs using docs.page and create the documentation for Button

docs: Document naked button

---

docs.json
docs/select.mdx
docs/textfield.mdx
packages/naked/example/lib/api/naked_select.0.dart
packages/naked/example/lib/api/naked_select.1.dart
packages/naked/example/lib/api/naked_textfield.0.dart
packages/naked/example/lib/examples/naked_select_example.dart
packages/naked/example/lib/main.dart
packages/naked/example/lib/main_example.dart
packages/naked/lib/src/naked_menu.dart
packages/naked/lib/src/naked_select.dart
packages/naked/lib/src/naked_tooltip.dart
packages/naked/lib/src/utilities/naked_portal.dart
packages/naked/lib/src/utilities/overlay_content_menu.dart
packages/naked/test/src/naked_select_test.dart

This PR refactors the select component and its related tests by renaming properties and updating the overlay management API.
Key changes include replacing pumpSelect with pumpMaterialWidget in tests, renaming overlayChildBuilder to overlayBuilder in multiple files, and updating select examples in both the library and documentation.

refactor: Select

---

docs/tooltip.mdx
packages/naked/example/lib/api/naked_tooltip.0.dart
packages/naked/example/lib/examples/naked_tooltip_example.dart
packages/naked/lib/src/naked_tooltip.dart
packages/naked/test/src/naked_tooltip_test.dart

This PR implements a new tooltip lifecycle mechanism with timing parameters and state change callbacks, refactoring both the widget API and the associated tests.
- Key changes include updating the NakedTooltip API to use internal state management (with new durations and onStateChange events)
- modifying tests to simulate hover events using a helper function, and revising examples and documentation accordingly.

feat: Implement Tooltip Lifecycle

---

docs/textfield.mdx
packages/naked/example/lib/api/naked_textfield.0.dart
packages/naked/lib/src/naked_textfield.dart

This PR introduces a new text style property to the NakedTextField widget and updates related documentation and examples to reflect parameter renamings and enhancements.
- Adds a new "style" parameter and associated logic to support custom text styling.
- Renames interaction callbacks (e.g., onPressedAlwaysCalled to onTapAlwaysCalled) and updates the builder function signature for clarity.
- Updates documentation and example code to match the new API changes.

feat: Add textstyle prop in NakedTextField
