btwld/mix

lib/mix.dart
lib/src/attributes/primitives/gestures/disabled.dart
lib/src/attributes/primitives/gestures/focused.dart
lib/src/attributes/primitives/gestures/hovering.dart
lib/src/attributes/primitives/gestures/pressing.dart
lib/src/mixer/mixer.dart
lib/src/utilities/utilities_api.dart
lib/src/widgets/primitives/pressable.dart

#1
Added `DisabledAttribute`, `FocusedAttribute`, `HoveringAttribute`, `PressingAttribute`.
```dart
Mix(
apply(_container),
pressing(Mix(bgColor(RxColors.primary))),
hovering(Mix(bgColor(RxColors.secondary))),
apply(RxShadows.shadow20),
)
```
I had to make `PressableMixerWidget` a stateful widget because the current api doesn't offer any type of state management.

Pressable Widget

---

lib/mix.dart
lib/src/mixer/mixer.dart
lib/src/widgets/primitives/icon.dart
lib/src/widgets/primitives/pressable.dart

Currently, when we have a `Pressable` widget, only its own mix is decorated according to its current state (disabled, pressing, hovering or focused).
Now, all the `Mix`es below it can access the current pressable state and change accordingly.
Let's use the following code as example:
```dart
Pressable(
_outlineMix,
onPressed: null,
child: IconMix(
Mix(
apply(_icon),
iconColor(Colors.primary),
disabled(Mix(iconColor(Colors.grey))),
hovering(Mix(iconColor(Colors.primary.shade400))),
pressing(Mix(iconColor(Colors.primary.shade600))),
),
icon: Icons.close,
),
),
```
| Previosly | Currently |
| ---------- | ---------- |
| ![old_button](https://user-images.githubusercontent.com/45696119/134026785-eb2e24cf-fcf7-4654-af0e-acbd44ae87bf.png) | …

PressableNotifier

---

lib/src/widgets/primitives/box.dart
lib/src/widgets/primitives/icon.dart
test/widgets/box_test.dart
test/widgets/icon_test.dart
test/widgets/text_test.dart

Currently IconMix throws an error is `iconSize` attribute is not specified.
This also fix the issues on the tests caused by the animation api!

Fix IconMix

---

demo/lib/app_shell.dart
demo/lib/views/pressable_preview.dart
lib/src/widgets/pressable.widget.dart

Fixes #59 
The `press` state was still being turned on while disabled. This pr verifies if it's enabled before setting the pressing state to true

Pressable: account for enabled on all pressing toggles

---

lib/src/attributes/variants/variants.utils.dart
lib/src/variants/variants.dart

When the new version of Mix was released, it came with break changes, one of them is the class `Variant` hasn't a constant constructor anymore, what don't allow to use the new format of enums with properties.
In this PR I fix this and `Variant` constructor become constant again.
Changing this:
```dart
enum SomaButtonAppearance {
primary(Variant("primary")),
secondary(Variant("secondary")),
ghost(Variant("ghost"));
const SomaButtonSize(this.variant);
final Variant variant;
}
```
To
```dart
enum SomaButtonAppearance{
primary,
secondary,
ghost;
Variant get variant {
switch (this) {
case primary:
return Variant("primary");
case secondary:
return Variant("secondary");
case ghost:
return Variant("ghost");
}
}
}
```

Turn Variant const again

---

lib/src/widgets/pressable/gesture_widget.dart

- By default PressableBox is already animated

PressableBox is animated by default

---

.gitignore
analysis_options.yaml
demo/pubspec.lock
lib/src/helpers/build_context_ext.dart
lib/src/specs/flex/flex_widget.dart
lib/src/specs/stack/stack_widget.dart
lib/src/utils/context_variant_util/on_breakpoint_util.dart
lib/src/utils/context_variant_util/on_orientation_util.dart
pubspec.lock
pubspec.yaml
test/src/helpers/build_context_ext_test.dart
test/src/utils/context_variant_util/on_orientation_util_test.dart
website/components/HomeContent.tsx

There is a breaking change for `const` and the `sizeOf` API used within mix that was incompatible with older versions of Flutter. i.e. `3.7.3`.
I have removed some of these in order to provide better support for older versions.

Fix incompatibility MediaQuery and Flex, Stack not const

---

lib/src/attributes/shadow/shadow_util.dart

Deprecate helper utilities for elevations; this option is a bit redundant. The initial purpose was meant to offer some type safety, but the syntax is too verbose.
- **Chore** (updating grunt tasks etc; no production code change)

Deprecate elevation helpers

---

CHANGELOG.md
lib/src/core/decorator.dart
lib/src/decorators/widget_decorators.dart

Closes #179 
Removed type of FlexWidgetDecorator as this is not needed, and Flexible can wrap different types of widgets

Removed type of FlexWidgetDecorator

---

lib/src/utils/style_recipe.dart
lib/src/widgets/pressable/pressable_widget.dart

- Remove function from widget tree;
- Rename `StyleRecipe.selectVariants()` to  `StyleRecipe.applyVariants()`

Remove function from Widget Tree

---

lib/src/attributes/decoration/decoration_dto.dart
lib/src/attributes/decoration/decoration_util.dart
lib/src/attributes/decoration/image/decoration_image_dto.dart
lib/src/attributes/decoration/image/decoration_image_util.dart
test/src/attributes/decoration/decoration_dto_test.dart
test/src/attributes/decoration/image/decoration_image_dto_test.dart
test/src/widgets/box/box_test.dart

* Implement support to `DecorationImage`

Support to decoration image

---

lib/src/attributes/color/color_util.dart
test/src/attributes/color/color_util_test.dart

Allows for use of directives directly on the color of ColorUtility

Added color directives to single colors

---

lib/src/specs/flex/flex_widget.dart
test/src/specs/flex/flex_widget_test.dart

- FlexBox doesn't duplicate the decorator anymore.

Fix more than one decorator on Flex widgets when decorators are used

---

lib/src/attributes/spacing/spacing_dto.dart
test/src/specs/container/box_util_test.dart

We cannot have the all method due to the directional comparison. Also all method was not setup correctly, and not been used by any utility.

Removed SpacingDto all method

---

lib/src/widgets/pressable/pressable_widget.dart
test/src/widgets/pressable/pressable_widget_test.dart

- Rename `disable` to `enabled`
- **New feature** (breaking change which adds functionality)

Rename disable to enabled

---

website/components/Features.tsx

Is it related to any opened issue?
This PR addresses the problem of broken links on the homepage by updating the URLs to their correct paths.
- Updated URL for the 'Design Token' link to '/docs/guides/design-token'

fix broken links on the homepage

---

packages/mix/lib/src/core/spec.dart
packages/mix_generator/build.yaml
packages/mix_generator/lib/mix_generator.dart

When not configuring to run each generator in a different file user ge4ts an error about conflict.
Generators are now a shared resource to avoid conflict and to allow them to run simultaneously.
- Spec is no longer a 

Fix: Resolved conflict on generators when not configured on build.yaml

---

melos.yaml
packages/mix/lib/src/attributes/border/border_dto.dart
packages/mix/lib/src/attributes/border/shape_border_dto.dart
packages/mix/lib/src/attributes/decoration/decoration_dto.dart
packages/mix/lib/src/attributes/decoration/decoration_dto.g.dart
packages/mix/lib/src/attributes/text_style/text_style_dto.g.dart
packages/mix/lib/src/specs/box/box_spec.dart
packages/mix/lib/src/specs/box/box_spec.g.dart
packages/mix/test/src/attributes/decoration/decoration_dto_test.dart

Merge behavior for BoxDecorationDto and ShapeDecorationDto is much more flexible and attempts to merge so users can reuse utilities like borderRadius and boxShape.

Fix: mix - Improved merge behavior between ShapeDecoration and BoxDecoration

---

melos.yaml
packages/mix/lib/src/attributes/attributes.dart
packages/mix/lib/src/attributes/gap/gap_dto.dart
packages/mix/lib/src/attributes/gap/gap_util.dart
packages/mix/lib/src/attributes/gap/spacing_side_dto.dart
packages/mix/lib/src/specs/flex/flex_spec.dart
packages/mix/lib/src/specs/flex/flex_spec.g.dart
packages/mix/test/src/specs/flex/flex_attribute_test.dart
packages/mix/test/src/specs/flex/flex_spec_test.dart
packages/mix/test/src/specs/flex/flex_util_test.dart

#326
`FlexSpecAttribute` didn't resolve correctly when using tokens.
- Create `GapDto`, `GapUtility`
- Change the Dto used in `FlexSpecAttribute`

fix: Gap resolve in flex attribute

---

packages/mix/lib/src/specs/flex/flex_widget.dart
packages/mix/test/src/specs/flex/flex_widget_test.dart

Exception on flex widget when there are no children and it tries to add a gap.

fix: Exception when there is no children on flex

---

packages/mix/lib/src/widgets/widget_state/pressable_widget.dart
packages/mix/test/src/widgets/pressable/pressable_widget_test.dart

#314 
Add the ability in Pressable and PressableBox to respond to keyboard events, specifically, space and enter.
- Add an `Actions` on `Pressable`'s build method.

feat: pressable supports keyboard events

---

melos.yaml
packages/mix/lib/src/attributes/border/shape_border_dto.dart
packages/mix/lib/src/core/factory/style_mix.dart
packages/mix/lib/src/specs/icon/icon_widget.dart
packages/mix/test/bechmarks/widget_build_test.dart
packages/mix/test/empty_widget.dart
packages/mix/test/helpers/testing_utils.dart

chore: Dart lint fixes

---

.github/workflows/add_label.yml
packages/mix/lib/src/attributes/text_style/text_style_dto.dart
packages/mix/lib/src/attributes/text_style/text_style_dto.g.dart
packages/mix/lib/src/attributes/text_style/text_style_util.dart
packages/mix/lib/src/core/helpers.dart
packages/mix/lib/src/specs/text/text_spec.dart
packages/mix/lib/src/theme/tokens/text_style_token.dart
packages/mix/test/helpers/testing_utils.dart
packages/mix/test/src/attributes/text_style/text_style_dto_test.dart
packages/mix/test/src/attributes/text_style/text_style_util_test.dart
packages/mix/test/src/theme/tokens/text_style_token_test.dart

Closes #369
- add a fontVariants
Add tests and utilities for fontVariants
This PR needs the Flutter bump (#365)

feat: add attribute to fontVariantion

---

packages/mix/lib/src/widgets/widget_state/pressable_widget.dart
packages/mix/test/src/widgets/pressable/pressable_widget_test.dart

Use timer instead of future<void>. Because of this, we can dispose the timer.
- Add a timer in `_MixStateWidgetBuilderState`

refactor: use timer instead of future<void>

---

packages/mix/lib/src/modifiers/render_widget_modifier.dart

closes #373 
Review the order of modifiers
Add FlexibleModifier, PaddingModifier, and RotatedModifier.

fix: add flexible as the first in the order of modifiers

---

packages/mix_lint/lib/mix_lint.dart
packages/mix_lint/lib/src/assists/extract_attributes.dart
packages/mix_lint/lib/src/utils/extensions/dart_file_edit_builder.dart

- This assist can extract a group of attributes from a style and wrap them in a variable called `extractedAttributes`.
- Add a folder called `assists`
- Create the first assist.
https://github.com/user-attachments/assets/533e263b-db80-46a3-ad44-304e2fd909f6
https://github.com/user-attachments/assets/50377d96-8c09-4912-8ac4-9c696caa2e49

feat: create an assist to extract attributes from a Style

---

packages/mix/lib/src/attributes/border/border_dto.g.dart
packages/mix/lib/src/attributes/enum/enum_util.g.dart
packages/mix/lib/src/attributes/scalars/scalar_util.g.dart
packages/mix/lib/src/attributes/spacing/edge_insets_dto.g.dart
packages/mix_generator/lib/src/builders/dto/class_utility_dto.dart
packages/mix_generator/lib/src/builders/method_lerp_builder.dart
packages/mix_generator/lib/src/builders/utility_class_builder.dart
packages/mix_generator/lib/src/helpers/builder_utils.dart
packages/mix_generator/lib/src/helpers/dart_type_ext.dart
packages/mix_generator/lib/src/helpers/type_ref_repository.dart
packages/mix_generator/lib/src/mixable_class_utility_generator.dart
packages/mix_generator/lib/src/mixable_enum_utility_generator.dart

Now you can add utility methods by defining them as static or constructor methods in the dto before generation

feat: Dto utility generation now adds constructor and static methods

---

packages/mix_lint/lib/src/assists/extract_attributes.dart
packages/mix_lint/lib/src/utils/visitors.dart

- Add new features to the assist "extract attributes" allowing extracting attributes from `TopLevelVariableDeclaration`, `FunctionDeclaration` and `MethodDeclaration`. 
- The new features include automatically adding 'late' at the beginning of a field when necessary, and '_' private to `TopLevelVariableDeclaration` and top-level getters.
- When attributes inside a variant's scope change it receives the name of the variant + "Variant"
- The assist was refactored

feat: Improvements for the "extract attributes" assist 

---

packages/mix/lib/src/core/styled_widget.dart
packages/mix/lib/src/modifiers/internal/render_widget_modifier.dart
packages/mix/test/helpers/override_modifiers_order.dart

- The StyledWidgets could not receive a list with `Specs` and `Attributes`.
- The unit test was enhanced to include tests for three scenarios: only `Specs`, only `Attributes`, and `Specs + Attributes`.
- The parameter "mix" is no longer deprecated. It is now used for normalization.

fix: normalization of order of modifier when applied to a Styled Widget

---

packages/mix/lib/src/attributes/border/shape_border_dto.dart

The classes for `StarBorder` and `LinearBorder` were created despite support for using them as utilities were not available.
- Add `star` and `linear` as attributes for `ShapeBorderUtility`.

fix: add star and linear to ShapeBorderUtility

---

packages/mix/lib/src/core/attribute.dart
packages/mix/lib/src/core/deprecation_notices.dart
packages/mix/lib/src/core/modifier.dart
packages/mix/lib/src/core/spec.dart
packages/mix/lib/src/variants/variant_attribute.dart
packages/mix/test/helpers/testing_utils.dart

Removed the `base` keyword from attributes for more flexibility on code gen.

chore: Removed base keyword from attributes

---

packages/mix/lib/src/specs/flex/flex_widget.dart
packages/mix/test/src/specs/flex/flex_widget_test.dart

This PR makes `FlexSpecWidget` prioritize the direction specified in the `FlexSpec`.
- Prioritize `direction` in `FlexSpec` instead of the parameter.
- This PR changes this behavior in all `Flex` alternatives.

fix: FlexSpecWidget prioritizes the direction in spec

---

packages/mix/lib/src/widgets/pressable_widget.dart
packages/mix/test/src/widgets/pressable/pressable_widget_test.dart

- Pressable was disposing the MixWidgetStateController, even when Pressable wasn't the instantiator.
- Add a conditional to verify if the Pressable was the one who instantiated.

fix: Pressable disposes controller only if it creates it

---

packages/mix/lib/src/widgets/pressable_widget.dart
packages/mix/test/src/widgets/pressable/pressable_widget_test.dart

- The `MouseRegion` inside `Interactable` was causing side effects on `HitTestBehavior`
- Change the order of `MouseRegionMixStateWidget` on the tree.

fix: HitTestBehavior when there is a Interectable in the tree

---

packages/remix/lib/components/button/button.dart
packages/remix/lib/components/button/button_blank.dart
packages/remix/lib/components/button/button_widget.dart
packages/remix/lib/helpers/component_builder.dart
packages/remix/test/components/button/button_widget_test.dart

- Button now supports building a spinner
- add a builder in RxButton and RxBlankButton

feat: button supports component builder

---

packages/mix/lib/src/modifiers/transform_widget_modifier.dart

- Transform.rotate was not able to be applied as a `specModifier`
- Fix applying the modifier through the builder

fix: Transform.rotate couldn't be applied as specModifiers

---

packages/mix/lib/src/core/spec.dart
packages/mix/lib/src/specs/box/box_spec.g.dart
packages/mix/lib/src/specs/flex/flex_spec.g.dart
packages/mix/lib/src/specs/icon/icon_spec.g.dart
packages/mix/lib/src/specs/image/image_spec.g.dart
packages/mix/lib/src/specs/stack/stack_spec.g.dart
packages/mix/lib/src/specs/text/text_spec.g.dart
packages/mix/test/src/specs/box/box_spec_test.dart
packages/mix_annotations/lib/src/annotations.dart
packages/mix_generator/lib/src/builders/method_lerp_builder.dart
packages/mix_generator/lib/src/helpers/annotation_helpers.dart

- SpecModifiers were taking half of the animation time to start the animation.
- Add the property `isLerpable` to the `@MixableProperty`
- Update the `mix_generator` to don't create any custom lerp when `isLerpable` is `false`
https://github.com/user-attachments/assets/b3ffd4ae-75ff-49b3-9a67-97b2e065aa15
https://github.com/user-attachments/assets/91561bf6-be06-4b49-88ee-733a61bb8cae

fix: SpecModifiers were taking a long time to animate.

---

packages/mix/lib/src/attributes/animated/animated_data.dart
packages/mix/lib/src/attributes/animated/animated_data_dto.dart
packages/mix/lib/src/core/factory/style_mix.dart
packages/mix/lib/src/core/spec.dart
packages/mix/lib/src/specs/box/box_spec.dart
packages/mix/lib/src/specs/box/box_spec.g.dart
packages/mix/lib/src/specs/flex/flex_spec.g.dart
packages/mix/lib/src/specs/icon/icon_spec.g.dart
packages/mix/lib/src/specs/image/image_spec.g.dart
packages/mix/lib/src/specs/stack/stack_spec.g.dart
packages/mix/lib/src/specs/text/text_spec.g.dart
packages/mix/test/src/specs/box/box_spec_test.dart
packages/mix/test/src/specs/box/box_widget_test.dart
packages/mix_annotations/lib/src/annotations.dart
packages/mix_generator/lib/src/builders/method_lerp_builder.dart
packages/mix_generator/lib/src/helpers/annotation_helpers.dart
packages/remix/lib/components/button/button.g.dart
packages/remix/lib/components/callout/callout.g.dart
packages/remix/lib/components/card/card.g.dart
packages/remix/lib/components/checkbox/checkbox.g.dart
packages/remix/lib/components/progress/progress.g.dart
packages/remix/lib/components/radio/radio.g.dart
packages/remix/lib/components/spinner/spinner.g.dart
packages/remix/lib/components/switch/switch.g.dart

- Before this PR there was no way to listen for when the animation was completed, which is a crucial part of animation in more complex components.
- Create the API `onEnd` for `AnimatedStyle`, which is called when the animation ends.

feat: Add parameter onEnd for AnimatedStyle

---

packages/mix/lib/src/core/factory/style_mix.dart

fixes GitHub syntax highlight
Is it related to any opened issue? No
Due to missing open code block in fn block, syntax highlight on github broken below this function
fixes the above issue

fix(docs): Fix fn level docs for Style::applyVariants

---

packages/mix/lib/src/theme/mix/mix_theme.dart

There are two ways to do that.
``` dart
instance.fold([themes...]) // require an existing instance.
MixThemeData.fold([themes...]) // auto instanciation
```
I found the second less intrusive but we can have both 
we just need to decide on good naming.

feat: Fold MixThemeData into single root

---

packages/mix/lib/src/modifiers/scroll_view_widget_modifier.dart
packages/mix/lib/src/modifiers/widget_modifiers_util.dart
packages/mix/lib/src/theme/mix/mix_theme.dart
packages/mix/test/src/modifiers/mouse_cursor_modifier_test.dart
packages/mix/test/src/modifiers/scroll_view_widget_modifier_test.dart
packages/mix/test/src/widgets/pressable/pressable_widget_test.dart
packages/mix/test/variants/context_variant_util/on_platform_util_test.dart
packages/mix_annotations/test/annotations_test.dart
packages/mix_generator/test/generated_code_test_cases/main.dart
packages/mix_lint/lib/mix_lint.dart

Chore ran linting for dart fix, and dcm.

chore: linting

---

packages/mix/lib/src/core/factory/style_mix.dart
packages/mix/test/src/factory/style_mix_test.dart

- When merge Style with an Animated style was not generating a AnimatedStyle 
- Add a logic to return an AnimatedStyle when merging Style and AnimatedStyle

fix: Style when merged with an AnimatedStyle should generate a AnimatedStyle

---

packages/mix/lib/src/attributes/modifiers/widget_modifiers_data_dto.dart
packages/mix/lib/src/attributes/modifiers/widget_modifiers_util.dart
packages/mix/lib/src/modifiers/scroll_view_widget_modifier.dart
packages/mix/test/src/attributes/modifiers/widget_modifiers_data_dto_test.dart

Create a way to remove all previous inline modifiers
- Create `_WidgetModifiersDataDtoCleaner` and modify the `merge` logic

feat: implement a way to clear inline modifiers

---

packages/mix/lib/mix.dart
packages/mix/lib/src/attributes/color/color_directives.dart
packages/mix/lib/src/attributes/color/color_directives_impl.dart
packages/mix/lib/src/attributes/color/color_dto.dart
packages/mix/lib/src/attributes/color/color_util.dart
packages/mix/lib/src/modifiers/scroll_view_widget_modifier.dart
packages/mix/test/src/attributes/color/color_directives_impl_test.dart
packages/mix/test/src/attributes/color/color_dto_test.dart
packages/remix/demo/lib/components/select_use_case.dart

- Add additional directives to customize colors, in addition to the capability to delete them.
- Refactor directives implementation
- Add 5 extra directives: `clearDirectives`, `withHue`, `withLightness`, `withSaturation`, and `withValue`.
- Add tests to validate the new logic added to tests

feat: Add more directives to Colors

---

packages/mix/lib/src/attributes/border/shape_border_dto.dart

- This PR allows the creation of a custom OutlinedBorder, which can be passed to your component through the Mix API
- OutlinedBorderDto become an `abstract` class
- Add a method call to `ShapeBorderUtility`
- Add the `abstract class CustomOutlinedBorder`
To create your custom OutlinedBorder, you should create a Dto for your border, look at the example:
```dart
@MixableDto()
final class MyCustomBorderDto extends OutlinedBorderDto<MyCustomBorder>
with _$MyCustomBorderDto {
const MyCustomBorderDto({
// ... The params
});
}
```
To complete the creation, you need to create and define your Border, extending the CustomOutlinedBorder
```dart
class MyCustomBorder extends CustomOutlinedBorder<MyCustomBorderDto> {
// implement the border...
}
```

feat: Add CustomOutlinedBorder's 

---

examples/todo_list/.gitignore
packages/mix/lib/src/core/widget_state/internal/mix_widget_state_builder.dart
packages/mix/lib/src/core/widget_state/widget_state_controller.dart
packages/mix/lib/src/variants/context_variant_util/on_util.dart
packages/mix/lib/src/variants/widget_state_variant.dart
packages/mix/test/src/widgets/widget_state/widget_state_controller_test.dart

- Add a new state to MixWidgetState called `error`.
- Add the new state and update some tests
```dart
class ExampleButton extends StatefulWidget {
const ExampleButton({super.key});
@override
State<ExampleButton> createState() => _ExampleButtonState();
}
class _ExampleButtonState extends State<ExampleButton> {
late final MixWidgetStateController controller;
@override
void initState() {
super.initState();
controller = MixWidgetStateController();
}
@override
void dispose() {
controller.dispose();
super.dispose();
}
@override
Widget build(BuildContext context) {
return Pressable(
onPress: () => controller.error = true,
controller: controller,
child: Box(
style: Style(
$box.chain
..padding.horizontal(16)
..padding.vertical(12)
..border.all(color: Colors.black) …
```

feat: Add state error on MixWidgetState

---

packages/mix/lib/src/attributes/border/shape_border_dto.dart
packages/mix/test/src/attributes/border/shape_border_dto_test.dart

- Rewrite the ShapeBorder merge to use polymorphism
- Create a function called adapt to convert a border to another.
- It also expose some APIs

refactor: ShapeBorder merge

---

packages/mix/lib/mix.dart
packages/mix/lib/src/attributes/enum/enum_util.dart
packages/mix/lib/src/attributes/enum/enum_util.g.dart
packages/mix/lib/src/attributes/scalars/scalar_util.dart
packages/mix/lib/src/attributes/scalars/scalar_util.g.dart
packages/mix/lib/src/attributes/text_height_behavior/text_height_behavior_dto.dart
packages/mix/lib/src/attributes/text_height_behavior/text_height_behavior_dto.g.dart
packages/mix/lib/src/specs/text/text_spec.dart
packages/mix/lib/src/specs/text/text_spec.g.dart
packages/mix/test/src/attributes/scalars/scalar_util_test.dart
packages/mix/test/src/attributes/text_height_behavior/text_height_behavior_dto_test.dart
packages/mix/test/src/deprecated/text_attribute_test.dart
packages/mix/test/src/deprecated/text_spec_test.dart
packages/mix/test/src/specs/text/text_attribute_test.dart
packages/mix/test/src/specs/text/text_spec_test.dart

before
```dart
$text.textHeightBehavior(
const TextHeightBehavior(
applyHeightToFirstAscent: false,
applyHeightToLastDescent: false,
),
)
```
now
```dart
$text.chain
..textHeightBehavior.heightToFirstAscent(false),
..textHeightBehavior.heightToLastDescent(false),
)
```
- Create a utility for this TextHeightBehavior and TextLeadingDistribution 
- Reorganize `scalar_util_test.dart` file

feat: Utilities for text height behavior

---

packages/mix/lib/src/attributes/scalars/curves.dart
packages/mix/lib/src/attributes/scalars/scalar_util.dart
packages/remix/lib/src/components/accordion/accordion_theme.dart
packages/remix/lib/src/components/card/card.dart
packages/remix/lib/src/components/card/card_widget.dart
packages/remix/lib/src/components/dialog/dialog.dart
packages/remix/lib/src/components/select/select_theme.dart
packages/remix/lib/src/components/switch/switch_style.dart
packages/remix/lib/src/components/switch/switch_widget.dart
packages/remix/lib/src/components/toast/toast_layer.dart

Improve SpringCurve, add a constructor using `mass,` `stiffness`and`dampingRatio.` There is one other constructor which uses duration to do the curve calculation
- Rewrite SpringCurve
- Recreate some animations

feat: Improve spring curve

---

website/pages/docs/tutorials/creating-a-widget.md

N/A
Adds `import 'package:flutter/widgets.dart';` to the button spec generation example for the generated `ButtonSpecTween` class.
- Adds `import 'package:flutter/widgets.dart';` to the button spec generation example for the generated `ButtonSpecTween` class. 
N/A

docs: Update creating-a-widget.md

---

packages/mix/lib/src/core/factory/mix_data.dart
packages/mix/test/src/core/factory/mix_data_test.dart

Token was not resolving correctly when the styled widget had inherited set to `true`, because the `_tokenResolver` was not being merged properly.
- The `MixData.merge` method was modified;
- Implemented a test specifically to handle this test.

fix: Token was not being resolved correctly

---

packages/remix/demo/build.yaml
packages/remix/demo/lib/main.directories.g.dart

Saw that the new Remix package is using Widgetbook.
A small improvement to the navigation, to make it less tedious to jump between use-cases.

refactor(remix): improve widgetbook navigation

---

packages/mix/lib/src/specs/box/box_widget.dart
packages/mix/lib/src/specs/image/image_widget.dart
packages/mix/lib/src/specs/text/text_spec.dart
packages/mix/lib/src/specs/text/text_widget.dart

- The API related to order of modifiers was not implemented correctly on Box and Image
- Add parameter order of modifiers
- Fix places where it was not implemented correctly

fix: Order of modifiers implementation on Box, Image and Text

---

packages/remix/lib/src/themes/fortaleza/components/button_theme.dart

Add four properties to enhance customization in the theme. The main purpose is to allow small style customizations without compromising the current style architecture. It will be only available for Fortaleza theme
- Add color, padding, textStyle and radius props that can override the style
- add an automation for color set

feat: improve Fortaleza Theme Customization

---

packages/remix/lib/src/components/toast/toast_layer.dart
packages/remix/lib/src/core/remix_app.dart

To use the `showToast` method, developers must wrap the component in a Scaffold. However, sometimes, you may need to call `showToast` using the ToastLayer of the WidgetApp, such as the material way.
Add a `ToastLayer` on Remix app

fix: Add ToastLayer on RemixAPp

---

docs.json
docs/accordion.mdx
docs/button.mdx
docs/checkbox.mdx
packages/naked/example/lib/api/naked_accordion.0..dart
packages/naked/example/lib/examples/naked_accordion_example.dart
packages/naked/example/lib/main.dart
packages/naked/lib/src/naked_accordion.dart
packages/naked/test/src/helpers/simulate_hover.dart
packages/naked/test/src/naked_accordion_test.dart

This PR refactors the accordion examples and related docs/tests to use the new trigger-builder API, standardizes opacity calls, renames private example classes to public, and adds official NakedAccordion documentation.
- Updated the `simulate_hover` test helper to use `MouseRegion` and its `cursor` property.
- Refactored `naked_accordion_example.dart` by replacing `_buildSection` and private widgets with a reusable `SectionWidget`, inline trigger closures, and public class names.
- Added a full API example (`naked_accordion.0..dart`) and updated documentation (`docs/accordion.mdx`, `docs.json`) plus renamed CodeGroup titles in other docs.

refactor: accordion

---

docs.json
docs/index.mdx

Adds a new `Getting Started` guide for the Naked UI library and wires it into the sidebar.
- Replaces the default docs.page template with an introduction to Naked, key features, and component list.
- Introduces Installation, Example, and Configuration sections with code snippets.
- Updates `docs.json` to include an “Introduction” sidebar group linking to the new index page.

docs: Add introduction documentation

---

docs/select.mdx
packages/naked/example/lib/api/naked_select.0.dart
packages/naked/example/lib/api/naked_select.1.dart
packages/naked/example/lib/api/naked_tooltip.0.dart
packages/naked/lib/src/naked_select.dart
packages/naked/lib/src/naked_tooltip.dart
packages/naked/lib/src/utilities/naked_portal.dart
packages/naked/test/src/naked_select_test.dart
packages/naked/test/src/naked_tooltip_test.dart

This PR refactors the overlay components in Naked to use a unified lifecycle interface and mixin, replacing manual controller handling with a generic `OverlayChildLifecycleState` and `OverlayChildLifecycleMixin`.
- Introduces `OverlayChildLifecycleState` enum and `OverlayChildLifecycleMixin` in naked_portal.dart
- Updates `NakedTooltip` and `NakedSelect` to implement the new interface and drive their visibility via the mixin
- Aligns tests, examples, and documentation by removing controller props in favor of onStateChange and removalDelay

feat: Add overlayLifecycle to select

---

docs/menu.mdx
docs/select.mdx
packages/naked/lib/src/naked_menu.dart
packages/naked/lib/src/naked_select.dart
packages/naked/test/src/naked_select_test.dart

This PR changes the default value of the autofocus property from `true` to `false` for `Menu` and `Select` components to improve the user interaction behavior. The changes update the widget constructors in the core library, adjust the expected values in unit tests, and update the documentation accordingly.
- Changed default autofocus in NakedSelect, NakedSelectTrigger, NakedSelectItem, and NakedMenu
- Updated expected output in the select unit tests
- Revised documentation to reflect the new autofocus default

fix: Change default `autofocus` to false in Menu and Select

---

.gitignore
examples/todo_list/lib/style/components/list_tile.dart
melos.yaml
packages/mix/CHANGELOG.md
packages/mix/lib/mix.dart
packages/mix/lib/src/core/factory/style_widgets_ext.dart
packages/mix/lib/src/core/styled_widget_deprecation.dart
packages/mix/lib/src/specs/flex/flex_widget.dart
packages/mix/lib/src/specs/flexbox/flexbox_widget.dart
packages/mix/lib/src/specs/stack/stack_widget.dart
packages/remix/demo/lib/components/card_use_case.dart

This PR deprecates the old `Styled*` widgets and methods in favor of new names, makes the children parameter on FlexBox optional, and centralizes deprecation messages and migration examples.
All deprecated widgets will be removed in v2.0.0.
This is a non-breaking change that maintains full backward compatibility.
- DEPRECATED: StyledRow → Use HBox instead
- DEPRECATED: StyledColumn → Use VBox instead
- DEPRECATED: StyledFlex → Use FlexBox instead
- DEPRECATED: StyledStack → Use ZBox instead
- DEPRECATED: Style.row() method → Use Style.hbox() instead
- DEPRECATED: Style.column() method → Use Style.vbox() instead
- FIX: FlexBox children parameter is now optional for better API compatibility
- FEAT: Added deprecation constants and migration examples
- DOCS: Updated example projects to use …

feat: deprecate styled widgets in favor of new naming conventions

---

.husky/pre-commit
melos.yaml
pubspec.yaml

- Activate husky git hooks properly with `dart run husky install`
- Update lint_staged configuration to use melos commands for consistency
- Improve pre-commit hook with better comments
- Configure git hooks path to use .husky directory  
- Update pubspec.yaml to use `melos run analyze` and `melos run fix` in lint_staged
- Add clearer comments to pre-commit hook script
- Leverage existing melos scripts for consistency across monorepo
- Consistent use of melos commands across the project
- Proper git hooks activation  
- Better organization and maintainability of pre-commit checks
- Runs analysis and fixes only on staged files for better performance
This PR contains ONLY the husky/lint_staged changes - no token refactoring or other modifications.

feat: enhance husky and lint_staged with melos integration

---

packages/mix/lib/src/specs/flex/flex_widget.dart
packages/mix/test/src/specs/flex/flex_widget_test.dart

This PR refactors the `FlexSpecWidget` by removing its custom spacing logic and relying on the built-in spacing property of the `Flex` widget.
- Removing the custom _buildChildren method and associated gap insertion logic
- Directly passing the spacing value via the new spacing property on Flex
- Removing the test case that previously validated the custom gap behavior

refactor: Remove custom spacing logic

---

packages/remix/demo/lib/blocks/auth.dart
packages/remix/lib/src/components/action/button/button_widget.dart
packages/remix/lib/src/components/content_presentation/label/label.dart
packages/remix/lib/src/components/content_presentation/label/label_widget.dart

This PR adds icon position support to RxButton and RxLabel components, allowing icons to be positioned at either the start or end of the label text.
- **RxLabel**: Added `IconPosition` enum with `start` and `end` options
- **RxLabel**: Added `iconPosition` parameter to control icon placement (defaults to `IconPosition.start`)
- **RxButton**: Updated constructor to use generic `icon` parameter instead of `leadingIcon`
- **RxButton**: Added `iconPosition` parameter support (defaults to `IconPosition.start`)
- **Demo**: Refactored auth block to use RxButton with SocialMediaButtonStyle instead of custom SocialMediaButton widget
- **Demo**: Updated text field properties from `placeholderText` to `hintText`
- **Demo**: Improved show/hide password button text logic
```dart
// Before
RxButton( …
```

feat: Add icon position support

---

packages/remix/lib/src/components/action/button/button_widget.dart
packages/remix/lib/src/components/content_presentation/chip/chip_widget.dart
packages/remix/lib/src/components/form/checkbox/checkbox_widget.dart
packages/remix/macos/Flutter/GeneratedPluginRegistrant.swift
packages/remix/test/components/button_test.dart
packages/remix/test/components/checkbox_test.dart
packages/remix/test/components/chip_test.dart
packages/remix/test/components/label_test.dart
packages/remix/test/utils/interaction_tests.dart

This PR adds a comprehensive test suite for the RxButton and RxLabel widgets and updates the button API to use a spinner builder callback.
- Introduces `interaction_tests.dart` with reusable interaction helpers.
- Adds `label_test.dart` covering RxLabel rendering and icon positioning.
- Adds `button_test.dart` covering RxButton constructors, styling, spinner behavior, and interactive states.
- Renames `spinnerWidget` to `spinnerBuilder` in `RxButton` and updates its loading overlay logic.

test: Create a test suite for RxButton and RxLabel

---

packages/remix/test/components/badge_test.dart
packages/remix/test/components/callout_test.dart
packages/remix/test/components/divider_test.dart
packages/remix/test/components/progress_test.dart
packages/remix/test/components/spinner_test.dart

This pull request adds comprehensive unit tests for several UI components in the `remix` package to ensure proper initialization, rendering, and styling. The tests cover constructors, raw initialization, and UI output validation for `RxBadge`, `RxCallout`, `RxDivider`, `RxProgress`, and `RxSpinner`.
* Added tests to verify proper initialization of `RxBadge` properties, including `label`, `icon`, `variants`, and `style`.
* Verified raw initialization and rendering of child widgets within `RxBadge.raw`.
* Ensured correct UI output, including rendering of `label` text and `icon`.
* Added tests to validate the initialization of `RxCallout` properties, such as `text`, `icon`, `variants`, and `style`.
* Tested raw initialization with custom child widgets for `RxCallout.raw`.
* Verified proper …

test: Add tests for RxBadge, RxCallout, RxDivider, RxProgress, RxSpinner

---

packages/mix/lib/src/core/styled_widget.dart
packages/mix/lib/src/core/widget_state/internal/mix_widget_state_builder.dart
packages/mix/lib/src/core/widget_state/widget_state_controller.dart
packages/mix/lib/src/variants/widget_state_variant.dart
packages/mix/test/src/core/mix_state/internal/gesture_mix_state_test.dart
packages/mix/test/src/core/mix_state/internal/interactive_mix_state_test.dart
packages/mix/test/src/widgets/pressable/pressable_widget_test.dart
packages/mix/test/src/widgets/widget_state/widget_state_controller_test.dart
packages/remix/lib/src/helpers/remix_builder.dart
packages/remix/test/components/radio_test.dart
packages/remix/test/utils/interaction_tests.dart

Refactors the MixWidgetState class and related references to MixWidgetStateModel across core, variants, and test files. This improves clarity and consistency in naming for widget state management.

refactor: Rename MixWidgetState to MixWidgetStateModel

---

packages/remix/demo/lib/api/overlay/tooltip.dart
packages/remix/lib/remix.dart
packages/remix/lib/src/components/overlay/tooltip.dart
packages/remix/lib/src/components/overlay/tooltip.g.dart
packages/remix/lib/src/components/overlay/tooltip_style.dart
packages/remix/lib/src/components/overlay/tooltip_widget.dart
packages/remix/test/components/tooltip_test.dart

Introduces a new RxTooltip component to the overlay package, including its implementation, default styling, and integration with the Mix system. Updates exports in remix.dart, provides a demo usage, and adds comprehensive widget tests for tooltip behavior and properties.
Is it related to any opened issue?
Please summarize the changes.

feat: Add RxTooltip component with styles and tests

---

packages/mix/lib/src/core/style_builder.dart
packages/mix/test/src/core/style_builder_test.dart

Adds an `inheritable` parameter to StyleBuilder that enables automatic style inheritance for descendant widgets. This allows parent StyleBuilders to pass their computed styles down to child widgets, enabling proper style cascading similar to CSS inheritance.
- **Backward compatible**: `inheritable` defaults to `false`, maintaining existing behavior
- **Proper style cascading**: Children inherit cumulative computed styles from parent
- **Framework integration**: Works seamlessly with animations, modifiers, and variants  
- **Performance optimized**: StyleProvider wrapper only added when `inheritable=true`
- **Scope-aware**: Child widgets can access inherited styles via `StyleProvider.maybeOf<T>(context)`
```dart
StyleBuilder<BoxSpec>(
style: parentStyle,
inheritable: true,  // Enable …
```

feat: add inheritable flag to StyleBuilder for style cascading

---

packages/mix/example/lib/api/animation/keyframe.heart.dart
packages/mix/example/lib/api/animation/phase.arrow.dart
packages/mix/lib/src/modifiers/transform_modifier.dart
packages/mix/lib/src/modifiers/widget_modifier_config.dart
packages/mix/lib/src/style/mixins/widget_modifier_style_mixin.dart
packages/mix/test/src/modifiers/transform_modifier_test.dart

This PR implements multi-transform support by decomposing the existing single TransformModifier into specialized modifiers for different transformation types (scale, rotate, translate, and skew).
- Refactors TransformModifier hierarchy with specialized subclasses
- Adds new specialized transform methods with clearer parameter naming
- Updates existing transform utility methods to use the new specialized APIs

feat: multi transform support

---

packages/mix/lib/src/core/spec_utility.dart
packages/mix/lib/src/core/utility_variant_mixin.dart
packages/mix/lib/src/specs/box/box_mutable_style.dart
packages/mix/lib/src/specs/box/box_style.dart
packages/mix/lib/src/specs/flex/flex_mutable_style.dart
packages/mix/lib/src/specs/flex/flex_style.dart
packages/mix/lib/src/specs/flexbox/flexbox_mutable_style.dart
packages/mix/lib/src/specs/icon/icon_mutable_style.dart
packages/mix/lib/src/specs/icon/icon_style.dart
packages/mix/lib/src/specs/image/image_mutable_style.dart
packages/mix/lib/src/specs/stack/stack_mutable_style.dart
packages/mix/lib/src/specs/stack/stack_style.dart
packages/mix/lib/src/specs/text/text_mutable_style.dart
packages/mix/lib/src/specs/text/text_style.dart
packages/mix/lib/src/style/mixins/animation_style_mixin.dart

- Standardizes all two-type-parameter mixins to use consistent `<StylerType, SpecType>` ordering
- Updates mixin definitions: AnimationStyleMixin, UtilityVariantMixin, and Mutable
- Updates all usage sites across 15 files to match new signatures
**Mixin Definitions Updated:**
- `AnimationStyleMixin<S extends Spec<S>, T extends Style<S>>` → `AnimationStyleMixin<T extends Style<S>, S extends Spec<S>>`
- `UtilityVariantMixin<S extends Spec<S>, T extends Style<S>>` → `UtilityVariantMixin<T extends Style<S>, S extends Spec<S>>`
- `Mutable<S extends Spec<S>, T extends Style<S>>` → `Mutable<T extends Style<S>, S extends Spec<S>>`
**Usage Sites Updated:**
- 5 AnimationStyleMixin usages in main style files
- 7 UtilityVariantMixin usages in mutable style files
- 7 Mutable usages in mutable style …

refactor: normalize mixin type parameter order for consistency

---

packages/mix/lib/src/core/style_widget.dart
packages/mix/lib/src/modifiers/box_modifier.dart
packages/mix/lib/src/specs/box/box_widget.dart
packages/mix/lib/src/specs/flexbox/flexbox_widget.dart
packages/mix/lib/src/specs/icon/icon_widget.dart
packages/mix/lib/src/specs/image/image_widget.dart
packages/mix/lib/src/specs/stack/stack_widget.dart
packages/mix/lib/src/specs/text/text_widget.dart
packages/mix/test/src/modifiers/box_modifier_test.dart
packages/mix/test/src/specs/box/box_widget_test.dart
packages/mix/test/src/specs/flexbox/flexbox_widget_test.dart
packages/mix/test/src/specs/icon/icon_widget_test.dart
packages/mix/test/src/specs/image/image_widget_test.dart
packages/mix/test/src/specs/stack/stack_widget_test.dart
packages/mix/test/src/specs/text/text_widget_test.dart

- Refactored `StyleWidget` to use `styleSpec` parameter instead of `spec` for better consistency
- Updated all Mix widget constructors to use unified `styleSpec` naming convention
- Deprecated StyleSpec extension methods with clear migration guidance
- Cleaned up redundant builder patterns and simplified widget creation
- Maintained backward compatibility through proper deprecation notices
- Changed `StyleWidget.spec` parameter to `StyleWidget.styleSpec` with type `StyleSpec<S>?`
- Updated widget classes: Box, FlexBox, RowBox, ColumnBox, ZBox, StyledText, StyledIcon, StyledImage
- Modified StyleSpecBuilder integration to use new parameter structure
- Deprecated all StyleSpec extension `call()` and `createWidget()` methods
- Updated deprecation messages to guide users to direct widget …

refactor: migrate StyleWidget to use styleSpec parameter for improved consistency

---

packages/mix/example/lib/api/context_variants/selected.dart
packages/mix/example/lib/api/context_variants/selected_toggle.dart
packages/mix/example/lib/components/chip_button.dart
packages/mix/lib/src/specs/box/box_style_api.md
packages/mix/lib/src/specs/flex/flex_style_api.md
packages/mix/lib/src/specs/flexbox/flexbox_style_api.md
packages/mix/lib/src/specs/icon/icon_style_api.md
packages/mix/lib/src/specs/image/image_style_api.md
packages/mix/lib/src/specs/stack/stack_box_style_api.md
packages/mix/lib/src/specs/stack/stack_style_api.md
packages/mix/lib/src/specs/text/text_style_api.md
packages/mix/lib/src/style/mixins/variant_style_mixin.dart
packages/mix/test/src/variants/variant_mixin_test.dart

Removes variant convenience methods that are not automatically managed by Mix's core widgets (Pressable, Box, etc.). This cleanup improves API clarity and prevents confusion about which states are actually supported.
The default Mix widgets (Pressable, Box, etc.) do not react to certain widget states because they are not automatically managed by the framework. Providing convenience methods for these states created confusion and implied functionality that wasn't present.
- **`onSelected`** - Not automatically managed by Pressable; requires manual state tracking
- **`onError`** - Not managed by Mix widgets
- **`onDragged`** - Not managed by Mix widgets  
- **`onScrolledUnder`** - Not managed by Mix widgets
- **`onHovered`** ✅ - Managed by Pressable via MixInteractionDetector
- …

refactor: remove unsupported widget state variants

---

packages/mix/example/lib/api/default_widgets/default_styled_text.dart
packages/mix/lib/src/core/providers/style_provider.dart
packages/mix/lib/src/core/style_builder.dart
packages/mix/test/src/core/style_builder_test.dart

Introduces `DefaultStyledText` and `DefaultStyledIcon` as convenience typedefs for `StyleProvider`, simplifying the provision of text and icon styles to descendant widgets. Adds an example demonstrating their usage and updates StyleBuilder to properly merge inherited styles. Includes new tests to verify widget state tracking with context variants.
- add `DefaultStyledText` and `DefaultStyledIcon`
- fix StyleProvider logic

feat: Add DefaultStyledText and DefaultStyledIcon typedefs

---

packages/mix/lib/mix.dart
packages/mix/lib/src/core/utility_variant_mixin.dart
packages/mix/lib/src/core/utility_widget_state_variant_mixin.dart
packages/mix/lib/src/specs/box/box_mutable_style.dart
packages/mix/lib/src/specs/box/box_style.dart
packages/mix/lib/src/specs/flex/flex_mutable_style.dart
packages/mix/lib/src/specs/flex/flex_style.dart
packages/mix/lib/src/specs/flexbox/flexbox_mutable_style.dart
packages/mix/lib/src/specs/flexbox/flexbox_style.dart
packages/mix/lib/src/specs/icon/icon_mutable_style.dart
packages/mix/lib/src/specs/icon/icon_style.dart
packages/mix/lib/src/specs/image/image_mutable_style.dart
packages/mix/lib/src/specs/image/image_style.dart
packages/mix/lib/src/specs/stack/stack_box_style.dart
packages/mix/lib/src/specs/stack/stack_mutable_style.dart
packages/mix/lib/src/specs/stack/stack_style.dart
packages/mix/lib/src/specs/text/text_mutable_style.dart
packages/mix/lib/src/specs/text/text_style.dart
packages/mix/lib/src/style/mixins/variant_style_mixin.dart
packages/mix/lib/src/style/mixins/widget_state_variant_mixin.dart
packages/mix/test/src/variants/variant_mixin_test.dart

This PR refactors the widget state variant functionality by extracting it into dedicated mixin files for better separation of concerns and code organization.
**Changes:**
- Created `UtilityWidgetStateVariantMixin` for utility classes with widget state variant methods
- Created `WidgetStateVariantMixin` for style classes with widget state variant methods  
- Applied these new mixins to all relevant style and utility classes (Box, Flex, FlexBox, Icon, Image, Stack, Text)
- Removed widget state variant methods from base `UtilityVariantMixin` and `VariantStyleMixin`
- Updated exports in `mix.dart`
**Benefits:**
- Clearer mixin hierarchy and separation of concerns
- Widget state variant functionality is now isolated and easier to maintain
- Improved code organization without changing public …

refactor: extract widget state variant mixins into separate files
